name: microphone_web
description: Web implementation of the platform interface for the microphone plugin.
version: 0.0.1
homepage: https://github.com/creativecreatorormaybenot/microphone/tree/master/microphone_web

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.2

  microphone_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

  microphone:
    path: ../microphone

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MicrophoneWeb
        fileName: microphone_web.dart

