name: microphone_web
description: >2-
  Web implementation of the platform interface for the microphone plugin.
version: 0.0.1+2
homepage: >2-
  https://github.com/creativecreatorormaybenot/microphone/tree/main/microphone_web

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  microphone_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

  microphone:
    path: ../microphone

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MicrophoneWeb
        fileName: microphone_web.dart
